services:
  deep-research:
    container_name: deep-research
    build: .
    env_file:
      - .env
    volumes:
      - ./:/app/
    ports:
      - "3000:3000"
    command: npm run server
    tty: true
    stdin_open: true
